// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WDA3.Models;

#nullable disable

namespace WDA3.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WDA3.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = "O001",
                            Address = "Hcm",
                            Name = "Van A",
                            Phone = "113"
                        },
                        new
                        {
                            Id = "O002",
                            Address = "HN",
                            Name = "Van B",
                            Phone = "114"
                        },
                        new
                        {
                            Id = "O003",
                            Address = "DN",
                            Name = "Van C",
                            Phone = "115"
                        });
                });

            modelBuilder.Entity("WDA3.Models.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductName");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = "O001",
                            ProductName = "Pepsi",
                            Price = 3,
                            Quantity = 10
                        },
                        new
                        {
                            OrderId = "O001",
                            ProductName = "Coce",
                            Price = 3,
                            Quantity = 5
                        },
                        new
                        {
                            OrderId = "O002",
                            ProductName = "Bun bo",
                            Price = 10,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("WDA3.Models.OrderDetail", b =>
                {
                    b.HasOne("WDA3.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WDA3.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
